# Generated by Django 2.2.6 on 2019-11-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='商品名称')),
                ('category', models.CharField(max_length=50, verbose_name='商品分类')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热卖')),
                ('price', models.FloatField(default=0, verbose_name='商品价格')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
        ),
    ]
